<?php

namespace App;

use App\Mail\ProjectCreated;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;

class Project extends Model
{
    protected $fillable = [
        'title', 'description', 'user_id'
    ];

//    protected $dispatchesEvents = [
//        'created' => ProjectCreated::class,
//    ];

//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::created(function ($project) {
//            Mail::to($project->user->email)->send(
//                new ProjectCreated($project)
//            );
//        });
//    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function addTask($description)
    {
        $this->tasks()->create($description);
    }
}
